# use Ganache's forked mainnet mode as the default network
# NOTE: The V3 tests file can be run on a ftm-main-fork with current addresses built in
#   However, currently AVAx is the only one with incentives so the V3Rewards tests should be run on an AVAX fork
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - iearn-finance/yearn-vaults@0.4.3-1
  - OpenZeppelin/openzeppelin-contracts@3.1.0

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@yearnvaults=iearn-finance/yearn-vaults@0.4.3-1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"

#dotenv: .env

reports:
  exclude_contracts:
    - SafeMath
